services:
  user-api:
    build:
      context: ppf-user-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8000"
    volumes:
      - ./ppf:/home/app/ppf
      - ./ppf-user-api/userApi:/home/app/userApi
      - ./ppf-user-api/usrLogin:/home/app/usrLogin
      - ./ppf-user-api/api:/home/app/api
      - ./db:/home/app/db
    command:
      - /bin/sh
      - -c
      - |
        rm -f db/db.sqlite3
        touch db/db.sqlite3
        python -m pip install --config-settings editable-mode=strict -e ppf
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

  route-api:
    build:
      context: ppf-route-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./ppf:/home/app/ppf
      - ./ppf-route-api/routeApi:/home/app/routeApi
      - ./ppf-route-api/api:/home/app/api
      - ./db:/home/app/db
    command:
      - /bin/sh
      - -c
      - |
        python -m pip install --config-settings editable-mode=strict -e ppf
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - user-api
