services:
  user-api:
    container_name: user-api
    build:
      context: ppf-user-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8000"
    env_file:
      - .env.debug
    volumes:
      - ./ppf:/home/app/ppf
      - ./ppf-user-api/userApi:/home/app/userApi
      - ./ppf-user-api/usrLogin:/home/app/usrLogin
      - ./ppf-user-api/emailSending:/home/app/emailSending
      - ./ppf-user-api/api:/home/app/api
      - ./db:/home/app/db
    command:
      - /bin/sh
      - -c
      - |
        python -m pip install --config-settings editable-mode=strict -e ppf
        python manage.py runserver 0.0.0.0:8000

  route-api:
    container_name: route-api
    build:
      context: ppf-route-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8000"
    env_file:
      - .env.debug
    volumes:
      - ./ppf:/home/app/ppf
      - ./ppf-route-api/routeApi:/home/app/routeApi
      - ./ppf-route-api/api:/home/app/api
      - ./db:/home/app/db
    command:
      - /bin/sh
      - -c
      - |
        python -m pip install --config-settings editable-mode=strict -e ppf
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - user-api

  payments-api:
    container_name: payments-api
    build:
      context: ppf-payments-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8083:8000"
    env_file:
      - .env.debug
    volumes:
      - ./ppf:/home/app/ppf
      - ./ppf-payments-api/paymentsApi:/home/app/paymentsApi
      - ./ppf-payments-api/api:/home/app/api
      - ./db:/home/app/db
    command:
      - /bin/sh
      - -c
      - |
        python -m pip install --config-settings editable-mode=strict -e ppf
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - route-api
