services:
  route-api:
    build:
      context: ppf-route-api
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./ppf-route-api/routeApi:/home/app/routeApi:ro
      - ./ppf-route-api/api:/home/app/api:ro
      - ./db:/home/app/db:rw
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  user-api:
    build:
      context: ppf-user-api
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - ./ppf-user-api/userApi:/home/app/userApi:ro
      - ./ppf-user-api/api:/home/app/api:ro
      - ./db:/home/app/db:rw
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"