services:
  route-api:
    image: ppf-route-api
    build:
      context: ppf-route-api
      dockerfile: Dockerfile
    container_name: route-api
    restart: unless-stopped
    ports:
      - "8080:8000"
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        python manage.py loaddata load_chargerTypes.json service_profiles.json

  user-api:
    image: ppf-user-api
    build:
      context: ppf-user-api
      dockerfile: Dockerfile
    container_name: user-api
    restart: unless-stopped
    ports:
      - "8081:8000"
    env_file:
      - .env

  admin-page:
    image: ppf-admin-page
    build:
      context: ppf-admin-page
      dockerfile: Dockerfile
    container_name: admin-page
    restart: unless-stopped
    ports:
      - "8082:8000"
    env_file:
      - .env

  chat-engine:
    image: ppf-chat-engine
    build:
      context: ppf-chat-engine
      dockerfile: Dockerfile
    container_name: chat-engine
    restart: unless-stopped
    ports:
      - "8083:8000"
    env_file:
      - .env
    volumes:
      - ./db/chatengine:/opt/chatengine
    environment:
      - ROUTE_API_URL=http://route-api:8000
      - USER_API_URL=http://user-api:8000

  payments-api:
    image: ppf-payments-api
    build:
      context: ppf-payments-api
      dockerfile: Dockerfile
    container_name: payments-api
    restart: unless-stopped
    ports:
      - "8084:8000"
    env_file:
      - .env
