
on:
 push:
    branches:
      - "#43-Configurar-Github-Action"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Instalar key para que el agent SSH del runner pueda ejecutar commandos de docker usando ssh
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.7.0
      with:
        key: ${{ secrets.SSH_AWS_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        # name: id_rsa # optional
        # config: ${{ secrets.CONFIG }} # ssh_config; optional
        # if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: Checkout of chat engine
      uses: actions/checkout@v4

    - name: SCP docker-compose to remote
      run: |
       scp docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/PPF
